
spring:
  application:
    name: ContributeToLearning

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

github:
  token: ${GITHUB_API_TOKEN}
  api-url: https://api.github.com